### PR TITLE
Convert tidy vcf file to use vcf output from full length files

### PR DESCRIPTION
**Pull request by ErinBecker**
This PR does the following: 

- [x] ensures that the vcf data files we are working with are the canonical final vcf files by replacing existing files with the files from the new [Figshare](https://figshare.com/articles/Data_Carpentry_Genomics_beta_2_0/7726454) submission. These were probably already the same, but I wanted to play it on the safe side.
- [x] updates input and output directory structure for tidy vcf script to use the data folder that is currently in the lesson repo
- [x] recreates tidy vcf output file based on these changes

These changes are to make it easier to work on the lessons locally and not have to worry about the file structure on the AMI. 

It also uses the vcf output from the full length fasta files, which we are not having the learners run during the workshop due to time constraints. With this model, learners will need to pull the full length vcf files out of the .solutions folder to do the R lesson. This follows the same model as we use in the Ecology workshop and other DC workshops (lessening dependencies between lessons in case a learner doesn't get the needed output).

### CODE REVIEW

**Comment by ErinBecker** [comment]
@taylorreiter FYI

**Comment by taylorreiter** [comment]
@ErinBecker would you like me to review/approve this, or would @JasonJWilliamsNY or @naupaka prefer to make sure it meets their needs?

**Comment by naupaka** [comment]
@taylorreiter I don't want to speak for @ErinBecker but think it's just an FYI so you are in the loop. I will be running through this to check it before merging so no need to do that on your part (unless you want to offer any feedback/suggestions, which would of course be most welcome!).

**Comment by ErinBecker** [comment]
This was just a head's up for you @taylorreiter to make sure you are aware of progress on the R side of these lessons. A review from @naupaka as the author of the vcf_clean_script would be very welcome.

**Comment by ErinBecker** [comment]
Excellent! Thanks for the review @naupaka!

**Pull request merged**
