### PR TITLE
bring in other episodes

### PR DESCRIPTION
**Pull request by ErinBecker**
This PR brings in content for episodes composed by @naupaka and @kpoterlowicz and does some reformatting to bring content into line with current lesson template. @naupaka to review and merge!

### CODE REVIEW

**Comment by naupaka** [comment]
Looks good to me! Thanks @ErinBecker

**Comment by naupaka** [comment]
Can't merge b/c don't have write access yet, but ready to do so when possible

**Comment by ErinBecker** [comment]
Sorry @naupaka! I had added you to the wrong team. You should have write access now.

**Comment by naupaka** [comment]
Thanks!

**Pull request merged**
